// types
export const CHANGE_MODAL = 'CHANGE_MODAL';
export const CHANGE_PRELOADER = 'CHANGE_PRELOADER';
export const CHANGE_REC_ITEMS = 'CHANGE_REC_ITEMS';
export const ADD_CART_ITEM_ID = 'ADD_CART_ITEM_ID';
export const ADD_ALL_ITEMS = 'ADD_ALL_ITEMS';
export const ADD_ITEMS_FAILURE = 'ADD_ITEMS_FAILURE';
export const ADD_IDS_FAILURE = 'ADD_IDS_FAILURE';
export const CHANGE_CART_ITEMS = 'ADD_CART_ITEMS';
export const UPDATE_TOTAL = 'UPDATE_TOTAL';
